### ISSUE TITLE
Lazy load tasks

### ISSUE THREAD

**Issue by raldred** [sindresorhus/load-grunt-tasks#34]
Hey guys.
This module saves the need for having to write npmLoadTask over and over which is great.
However it really hurts performance especially for task that fork such as sass / coffeescript generation.

There's a nice little module called https://github.com/raphaeleidus/grunt-lazyload which has helped us in the past shave heaps of time off initialisation.

Would it be possible to incorporate in some way?

**Comment by sindresorhus** [comment]
No thanks. I've looked into it before, but turned out the small saving wasn't worth it.

I also don't see how forking for sass/coffeescript has anything to do with loading perf as the forking is done when the task is run, not loaded.

If you're looking for something highly performant grunt is definitely not it anyways as it's fully synchronous and inherently inefficient. Try gulp or broccoli.

**Comment by raldred** [comment]
For one time tasks sure it's not a big deal but when you're using eg. sass
as as a sub task of watch the time saving can be seconds and that's a
serious time sink for some of the guys on my team when we're making small
tweaks to css.
I appreciate your time nevertheless.

**Comment by thegregthomp** [comment]
I just struggled with slow watch tasks and this is exactly it. This plugin is a nice-to-have but it's pretty much unusable with 'watch' and sass/less. It takes 4 seconds to load tasks and 500ms for the actual task to run vs loading the stuff the old school way it takes 1 second to load tasks.
