### ISSUE TITLE
Plugin it's not looking for the node_modules in the same folder as the packages.json.

### ISSUE THREAD

**Issue by martuanez** [sindresorhus/load-grunt-tasks#47]
When a custom path is given for the package.json the plugin is not able to find the node_modules folder

**Comment by sindresorhus** [comment]
What custom path are you giving it? Can you provide some code?

**Comment by martuanez** [comment]
```require('load-grunt-tasks')(grunt, {config: '../package.json'});```

**Comment by sindresorhus** [comment]
Works for me.

**Comment by kahluagenie** [comment]
I think what @martuanez is saying is that when you give a custom package.json path, it doesn't look for node_modules at **that file's** level. It still looks at the default node_modules for the whole project. As an example, let's say my dependency is this Builder npm package. Builder depends on some grunt plugins that it loads like so:
`require('load-grunt-tasks')(this.grunt, {config: Path.resolve(__dirname, '../package.json')});`

Now let's assume I'm on npm2 (nested dependency dir structure). So when I bring in Builder as a dependency into my other project and invoke that code, it's still looking in the root node_modules for my project instead of looking at node_modules for that custom `'../package.json'` location. Which might be working as designed due to the nature of npm, but wasn't apparently obvious to me. I expected it to load out of that custom path, not just scan for dependencies in that package.json.

**Comment by martuanez** [comment]
That's what I tried to explain

**Comment by adampetrie** [comment]
I came across this same issue - is this the intended behaviour? If so, what is the benefit of passing in a path to the `package.json` file?
