### ISSUE TITLE
os.tmpDir() is deprecated

### ISSUE THREAD

**Issue by HopefulLlama** [sindresorhus/load-grunt-tasks#59]
Using `require('load-grunt-tasks')(grunt);` as expected throws the following warning:

```
(node:33960) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

Unsure if this is called by `load-grunt-tasks` directly, or some nested dependency.

**Comment by sindresorhus** [comment]
It's from a dependency as I don't use that. The package is on its latest dependencies, so either fixed or needs to be fixed in a dependency. You can check where the deprecation is coming from: https://www.google.com/search?q=node.js+trace+deprecation&oq=node.js+trace+deprecation&aqs=chrome..69i57j69i60j69i65l2j69i60j69i61.3704j0j1&sourceid=chrome&ie=UTF-8
